name = "mines-api"
main = "src/worker.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
PARTNER_URL = "https://lkfg.pro/8c330c1d"
ADMIN_IDS = "5947697192"
SETUP_SECRET = "kardan1488"

[[d1_databases]]
binding = "DB"
database_name = "mines-db"
database_id = "46382ec4-23b8-4da2-a902-faff6897d2ad"
